name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@gzdev
        with:
          apt-dependencies: 'pkg-config libprotobuf-dev protobuf-compiler libprotoc-dev libzmq3-dev uuid-dev libsqlite3-dev libignition-cmake2-dev libignition-math6-dev libignition-msgs6-dev libignition-tools-dev'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          gzdev_project_name: ignition-transport
